export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_DATA_RECEIVED = "EVENT/METRICS_DATA_RECEIVED";
export const METRICS_FILTER_RECEIVED = "EVENT/METRICS_FILTER_RECEIVED";
export const TRACKER_VALUES_RECEIVED = "EVENT/TRACKER_VALUES_RECEIVED";
// export const TRACKER_POSITION_RECEIVED = "EVENT/TRACKER_POSITION_RECEIVED";
// export const TUBING_DATA_RECEIVED = "EVENT/TUBING_DATA_RECEIVED";
// export const CASING_DATA_RECEIVED = "EVENT/CASING_DATA_RECEIVED";